# Generated by Django 5.1.6 on 2025-02-26 12:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dblcrdx9m/image/upload/v1740573867/profile_dqj2kj.png', max_length=255, null=True, verbose_name='users/'),
        ),
    ]
